### ISSUE TITLE
[Feature] Output Directory

### ISSUE THREAD

**Issue by RSS1102** [farm-fe/farmup#19]
Is there a parameter that can specify the output directory
such as:
```shell
farmup --out dist index.ts
```

**Comment by shulandmimi** [comment]
thanks for your issues, it already add at `v0.0.9`, your can reinstall and use it

```shell
farmup -o ./build
# or
farmup --output ./build
```

**Comment by RSS1102** [comment]
> thanks for your issues, it already add at `v0.0.9`, your can upgrade and use it
> 
> ```shell
> farmup -o ./build
> # or
> farmup --output ./build
> ```
good,Next time there is a new feature that  can I try it?😃😃

**Comment by shulandmimi** [comment]
> good,Next time there is a new feature that can I try it?😃😃

you can try it #22

**Comment by RSS1102** [comment]
> > good,Next time there is a new feature that can I try it?😃😃
> 
> you can try it #22

ok
